### ISSUE TITLE
Update ember-template-lint to latest version.

### ISSUE THREAD

**Issue by luketheobscure** [binhums/linter-ember-template#10]
Looks like ember-template-lint is up to v0.6.x. It would be rad to get this updated.

**Comment by binhums** [comment]
Hey @luketheobscure, thanks for the heads up. Will do.

**Comment by binhums** [comment]
If you're interested in learning about atom development we can pair on this together.

**Comment by binhums** [comment]
Thanks for the prompt, sorry it took a while to get round to. Published in v0.2.0.
